#FROM python:3.7
#WORKDIR /code
#ENV PYTHONUNBUFFERED=1
#COPY requirements.txt /tmp/
#RUN pip install -r /tmp/requirements.txt
#CMD python petfamily/manage.py migrate \
#&& python petfamily/manage.py runserver 0:8000

FROM python:3.7
WORKDIR /code
ENV PYTHONUNBUFFERED=1
COPY wait.sh /wait.sh
RUN chmod +x /wait.sh
COPY requirements.txt /tmp/

RUN pip install -r /tmp/requirements.txt
ADD ./ /code
CMD /wait.sh db 5432 \
  && python petfamily/manage.py collectstatic --noinput \
  && python petfamily/manage.py migrate \
  && python petfamily/manage.py migrate --run-syncdb \
  && /usr/local/bin/uwsgi --ini /code/uwsgi.ini
