# version: '3'
# services:

#   # frontend web server
#   web:
#     build:
#       context: .
#       dockerfile: Dockerfile-web
#     ports:
#       - "8080:80"
#     volumes:
#       - ./:/code:ro

#   # database server
#   db:
#     image: "postgres:latest"


#version: '3'
#services:
#  app:
#    build:
#      context: .
#      dockerfile: Dockerfile-devel
#    ports:
#      - "8000:8000"
#    volumes:
#      - ./:/code:ro
#    environment:
#      DJANGO_MODE: devel # look at os.environ['DJANGO_MODE'] to detect deployment
version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile-devel
    volumes:
      - static:/static:rw
    environment:
      DJANGO_MODE: production
  db: 
    image: "postgres:latest"
    volumes:
      - db:/var/lib/postgresql/data:rw
    environment:
      POSTGRES_USER: project
      POSTGRES_PASSWORD: secret
  web:
    build:
      context: .
      dockerfile: Dockerfile-web
    ports:
      - "8080:80"
    volumes:
      - static:/static:ro

volumes:
  static:
  db:
